### PR TITLE
Master

### PR DESCRIPTION
**Pull request by strideynet**
Whizzed up a slightly better then plain white texture for NATO. I will work on a better one in future. Arma 2 has literally the worst templates for texturing...

### CODE REVIEW

**Comment by strideynet** [comment]
Ignore this for now. TexViews deleted my progress.....

**Comment by strideynet** [comment]
Fixed

**Comment by strideynet** [comment]
http://steamcommunity.com/profiles/76561198065161712/screenshot/305489015275257273

**Comment by LexTheGreat** [comment]
Going to close this, we have a nato SUV skin at the moment.

**Comment by strideynet** [comment]
Ah yes. It seems it was added outside of the github explaining my confusion.

**Pull request closed without merging**
